# Generated by Django 3.2.7 on 2021-09-15 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natureapp', '0002_post_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='cat.jpg', upload_to='images'),
        ),
    ]
