# Generated by Django 3.2.7 on 2021-09-18 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natureapp', '0005_auto_20210915_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default='1234 Fake Drive, Portland Oregon, 97065', max_length=255),
        ),
    ]
